# Generated by Django 4.1 on 2022-08-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_application'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='ApplicationBidding',
        ),
        migrations.AlterModelOptions(
            name='applicationbidding',
            options={'verbose_name': 'Заявка на торги', 'verbose_name_plural': 'Заявки на торги'},
        ),
        migrations.AlterField(
            model_name='bidding',
            name='docs',
            field=models.FileField(blank=True, default='docs/bidding/no_docs.txt', upload_to='docs/bidding/', verbose_name='docs'),
        ),
    ]
