# Generated by Django 4.1 on 2022-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0003_rename_application_applicationbidding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationbidding',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='docs',
            field=models.FileField(upload_to='docs/bidding/', verbose_name='docs'),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='image',
            field=models.ImageField(upload_to='images/bidding/', verbose_name='image'),
        ),
    ]
