# Generated by Django 4.1 on 2022-09-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0004_alter_applicationbidding_phone_alter_bidding_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationbidding',
            name='tick',
            field=models.BooleanField(verbose_name='tick'),
        ),
    ]
