version: "3.9"
services:
  app:
    image: alekseevski
    container_name: alekseevski
    volumes:
      - media:/code/media
      - static:/code/static
    restart: always
    ports:
      - "5999:8000"

volumes:
  media:
  static: