version: "3.9"
services:
  app:
    image: alekseevski
    container_name: alekseevski
    restart: always
    ports:
      - "5999:8000"

#    env_file:
#      - .env
#    environment:
#      - SECRET_KEY=${SECRET_KEY}
#      - NAME=${NAME}
#      - USER=${USER}
#      - PASSWORD=&{PASSWORD}
#      - HOST=&{HOST}
#      - PORT=&{PORT}


