# Generated by Django 4.1 on 2022-08-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_photo_news_image_alter_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
