# Generated by Django 4.1 on 2022-08-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
