# Generated by Django 4.1 on 2022-08-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='item_url',
        ),
    ]
