# Generated by Django 4.1 on 2022-08-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_news_big_text_remove_news_small_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
