# Generated by Django 4.1 on 2022-08-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='images/news/no_image.jpg', upload_to='images/news/', verbose_name='image'),
        ),
    ]
