# Generated by Django 4.1 on 2022-08-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='images/news/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.BooleanField(verbose_name='publish'),
        ),
    ]
