# Generated by Django 4.1 on 2022-12-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_image_alter_news_publish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
