# Generated by Django 4.1.4 on 2022-12-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_news_date_alter_news_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='address',
            field=models.TextField(default=1, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
