# Generated by Django 4.1.4 on 2022-12-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_news_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='images/no_image.jpg', upload_to='images/news/', verbose_name='Изображение'),
        ),
    ]
