# Generated by Django 4.1 on 2022-09-14 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('text', models.TextField(verbose_name='text')),
            ],
            options={
                'verbose_name': 'Вакасния',
                'verbose_name_plural': 'Вакансии',
            },
        ),
        migrations.CreateModel(
            name='ApplicationVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('description', models.TextField(verbose_name='description')),
                ('docs', models.FileField(upload_to='vacancies/', verbose_name='docs')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_vacancy', to='vacancies.vacancy')),
            ],
            options={
                'verbose_name': 'Заявка на вакансию',
                'verbose_name_plural': 'Заявки на вакансии',
            },
        ),
    ]
