# Generated by Django 4.1 on 2022-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationvacancy',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='applicationvacancy',
            name='docs',
            field=models.FileField(blank=True, upload_to='vacancies/', verbose_name='docs'),
        ),
    ]
