# Generated by Django 4.1 on 2022-09-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0003_alter_applicationvacancy_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
    ]
