# Generated by Django 4.1 on 2022-12-19 11:07

import apps.base.services
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0004_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationvacancy',
            options={'verbose_name': 'Заявку на вакансию', 'verbose_name_plural': 'Заявки на вакансии'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансию', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='applicationvacancy',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='applicationvacancy',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='vacancies/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'doc', 'docx']), apps.base.services.validate_size_file], verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='applicationvacancy',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicationvacancy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='applicationvacancy',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='text',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
