# Generated by Django 4.1.4 on 2022-12-29 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_alter_applicationvacancy_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='text',
        ),
        migrations.AlterField(
            model_name='applicationvacancy',
            name='vacancy',
            field=models.CharField(max_length=100, verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название вакансии'),
        ),
    ]
