# Generated by Django 4.1 on 2022-08-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_remove_customer_email_remove_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
