# Generated by Django 4.1.4 on 2022-12-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='lat',
            field=models.CharField(default=1, max_length=255, verbose_name='Ширина'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addresses',
            name='long',
            field=models.CharField(default=1, max_length=255, verbose_name='Длина'),
            preserve_default=False,
        ),
    ]
