# Generated by Django 4.1 on 2022-08-25 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='publish',
        ),
    ]
