# Generated by Django 4.1 on 2022-12-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='publish',
        ),
    ]
