# Generated by Django 4.1 on 2022-12-19 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_products_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.products'),
        ),
    ]
