# Generated by Django 4.1 on 2022-08-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=255, verbose_name='inn')),
                ('organization', models.CharField(max_length=255, verbose_name='organization')),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('tick', models.BooleanField(default=False, verbose_name='tick')),
            ],
            options={
                'verbose_name': 'Заявка на закупку',
                'verbose_name_plural': 'Заявки на зкупку',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('text', models.TextField(verbose_name='text')),
                ('image', models.ImageField(blank=True, default='images/purchase/no_image.jpg', upload_to='images/purchase/', verbose_name='image')),
                ('docs', models.FileField(blank=True, default='docs/purchase/no_docs.txt', upload_to='docs/purchase/', verbose_name='docs')),
            ],
            options={
                'verbose_name': 'Закупка',
                'verbose_name_plural': 'Закупки',
            },
        ),
    ]
