# Generated by Django 4.1 on 2022-09-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_applicationpurchase_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='docs',
            field=models.FileField(upload_to='docs/purchase/', verbose_name='docs'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='image',
            field=models.ImageField(upload_to='images/purchase/', verbose_name='image'),
        ),
    ]
